#define SSL_CERTIFICATE \
"-----BEGIN CERTIFICATE-----\n" \
"MIIEQDCCAyigAwIBAgISA/9G/V+TM7P7vDQPSFrD4BAZMA0GCSqGSIb3DQEBCwUA\n" \
"MDIxCzAJBgNVBAYTAlVTMRYwFAYDVQQKEw1MZXQncyBFbmNyeXB0MQswCQYDVQQD\n" \
"EwJSMzAeFw0yMzEyMzEwNjMxNTVaFw0yNDAzMzAwNjMxNTRaMBsxGTAXBgNVBAMT\n" \
"EGRpc21vdW50ZWQuc3BhY2UwWTATBgcqhkjOPQIBBggqhkjOPQMBBwNCAASgWdP+\n" \
"9ZKt9ws3sYABTFAHmJL6mvLqrt3IRtnTaxNqN5aXsEJudri1P8vzf5xHeyWNQGyP\n" \
"sMaN+66MYwh43PYOo4ICMDCCAiwwDgYDVR0PAQH/BAQDAgeAMB0GA1UdJQQWMBQG\n" \
"CCsGAQUFBwMBBggrBgEFBQcDAjAMBgNVHRMBAf8EAjAAMB0GA1UdDgQWBBTOqw9V\n" \
"YQh/zSxx9GBKFQZxX2XZBjAfBgNVHSMEGDAWgBQULrMXt1hWy65QCUDmH6+dixTC\n" \
"xjBVBggrBgEFBQcBAQRJMEcwIQYIKwYBBQUHMAGGFWh0dHA6Ly9yMy5vLmxlbmNy\n" \
"Lm9yZzAiBggrBgEFBQcwAoYWaHR0cDovL3IzLmkubGVuY3Iub3JnLzA4BgNVHREE\n" \
"MTAvghBkaXNtb3VudGVkLnNwYWNlghtwaHBteWFkbWluLmRpc21vdW50ZWQuc3Bh\n" \
"Y2UwEwYDVR0gBAwwCjAIBgZngQwBAgEwggEFBgorBgEEAdZ5AgQCBIH2BIHzAPEA\n" \
"dgBIsONr2qZHNA/lagL6nTDrHFIBy1bdLIHZu7+rOdiEcwAAAYy+yVjiAAAEAwBH\n" \
"MEUCIQDxEyV5+JqUfSOzUpk169cZB+MWoas4ENDciLjIGLjeFwIgErxVQWDbpANq\n" \
"KRe0ZOlrtUMvpowBkwPIuQ3pKFDi+a4AdwA7U3d1Pi25gE6LMFsG/kA7Z9hPw/TH\n" \
"vQANLXJv4frUFwAAAYy+yVjrAAAEAwBIMEYCIQD2D3yQLsCx1DkJfP1j8nB2Fv19\n" \
"9FmpNsXPnqfWF5SJlAIhAL8NnmB88sdytkzKqUfTFstFq02EnQe3XhPH25TroF7u\n" \
"MA0GCSqGSIb3DQEBCwUAA4IBAQAdDC7AD5U/QMLj3AWRpTyZht7Y6GYGewFycGZs\n" \
"suORhLsDYM3/WyPPd0VcpcPRWmQbGVMmqmuHRkRk95XxRt4Em96DKAP43qCAUgxk\n" \
"PJN0ypmKpWZe7AKcx1tg07jnm6Gou4P/Chxj9VMnuUyk0NdDJyHQfA+wnRNPFCi/\n" \
"ggwgbnAfvdKsPuUX3NIeGWgOuSPM9C9we31Ke1+mP6l4PHeL3e8cnYnhCsesDi+x\n" \
"9rxHP85i6EZ+Hv46cvvk+gjYed2wo9iUjA1N2uYOv5lalGzHYhG4ri7V22RKuvKz\n" \
"7d8NagKakH76gHpf4IQaN/3ykq6fUgbVgCSBqgZyaOE5Yzly\n" \
"-----END CERTIFICATE-----\n"
