name: Deploy to Tomcat

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: self-hosted
      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14' # Change to your desired Node.js version

      - name: Install dependencies for Svelte app
        run: |
          cd /svelte/
          npm install
        working-directory: /svelte/

      - name: Build Svelte app
        run: |
          cd /svelte/
          npm run build
        working-directory: /svelte/

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '17' # Change to Java 17

      - name: Build Spring Boot project
        run: |
          ./mvnw clean package -DskipTests
        # working-directory: path/to/your/spring-boot-app

      - name: Deploy to Tomcat
    - name: Move WAR to Tomcat webapps
  run: |
    mkdir /opt/tomcat/webapps/beehive
  run: |
    mv ./target/master-0.0.1-SNAPSHOT.war /opt/tomcat/webapps/beehive/


