name: Build and Release

on:
  push:
    branches:
      - master

jobs:
  build-and-release:
    runs-on: self-hosted
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

        
    - name: Build with Maven
      run: mvn clean package

    - name: Generate Changelog
      run: echo "# Release notes for this version" > ${{ github.workspace }}/CHANGELOG.txt


    #https://github.com/marvinpinto/action-automatic-releases
    - name: Release
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          automatic_release_tag: "latest"
          title: "1.0.0"
          files: |
            target/*.war

