name: Build and Release

on:
  push:
    branches:
      - master

jobs:
  build_and_release:
    runs_on: self-hosted
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Generate build number
      id: buildnumber
      uses: onyxmueller/build-tag-number@v1
      with:
        token: ${{secrets.github_token}}

    - name: Print new build number
      run: echo "Build number is ${{ steps.buildnumber.outputs.BUILD_NUMBER }}"

    - name: Build with Maven
      run: mvn clean package

    - name: Create Release and Upload WAR
      run: |
        gh release create v${{ steps.buildnumber.outputs.BUILD_NUMBER }} target/*.war --title "Release v${{ steps.buildnumber.outputs.BUILD_NUMBER }}" --notes "Release notes for v${{ steps.buildnumber.outputs.BUILD_NUMBER }}"
      env:
        GH_TOKEN: ${{secrets.github_token}}
