name: Build and Release

on:
  push:
    branches:
      - master

jobs:
  build-and-release:
    runs-on: self-hosted
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      

    # - name: Generate build number
    #   uses: onyxmueller/build-tag-number@v1
    #   with:
    #     token: ${{secrets.DEFAULT}}        
    # - name: Print new build number
    #   run: echo "Build number is $BUILD_NUMBER"
      
    - name: Build with Maven
      run: mvn clean package

    - name: Generate Changelog
      run: echo "# Release notes for this version" > ${{ github.workspace }}/CHANGELOG.txt

    - name: Create Release and Upload WAR
      uses: softprops/action-gh-release@v1
      with:
        body_path: ${{ github.workspace }}/CHANGELOG.txt
        files: target/*.war
        token: ${{ secrets.DEFAULT }}

          
