name: Build and Release

on:
  push:
    branches:
      - master

jobs:
  build-and-release:
    runs-on: self-hosted
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js 18
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        
    - name: Build Svelte Frontend
      working-directory: svelte/
      run: |
        npm install
        npm run java
        
    - name: Build with Maven
      run: mvn clean package

    - name: Determine version
      id: versioning
      run: |
        echo "::set-output name=version::v$(git rev-list --count HEAD)_$(git rev-parse --short HEAD)"
    
    - name: Generate Changelog
      run: echo "# Release notes for version ${{ steps.versioning.outputs.version }}" > ${{ github.workspace }}/CHANGELOG.txt

    #https://github.com/marvinpinto/action-automatic-releases
    - name: Release
      uses: "marvinpinto/action-automatic-releases@v1.2.1"
      with:
          repo_token: "${{ secrets.DEFAULT }}"
          prerelease: false
          automatic_release_tag: "${{ steps.versioning.outputs.version }}"
          title: "${{ steps.versioning.outputs.version }}"
          files: |
            target/*.war

    - name: Remove existing ROOT.war and ROOT/ directory
      run: |
        echo "github" | sudo -S rm -f /opt/tomcat/apache-tomcat-10.1.13/webapps/ROOT.war
        echo "github" | sudo -S rm -rf /opt/tomcat/apache-tomcat-10.1.13/webapps/ROOT/


    - name: Rename .war to ROOT.war
      run: mv target/*.war target/ROOT.war

    - name: Deploy to local Tomcat
      run: cp target/ROOT.war /opt/tomcat/apache-tomcat-10.1.13/webapps/
